# Our build command used to include "bundle" to support Asciidoc format, 
# making sure Asciidoctor gets installed, now Netlifty seems to take care of it
[build]
  publish = "public"
  command = "hugo"
  HUGO_ENABLEGITINFO = "true"

# The Production Context applies to the branch you have configured as main branch to deploy:
[context.production.environment]
  HUGO_VERSION = "0.63.2"
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://docs.suitecrm.com/"

# The Deploy Preview Context applies to every Deploy Preview you create: 
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.63.2"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

# The Branch Deploy Context applies to all non-master branches deployed, whether they are in a Deploy Preview or not:
[context.branch-deploy.environment]
  HUGO_VERSION = "0.63.2"

# Besides these three predefined contexts, you can also use branch names as context names:
[context.preview.environment]
  HUGO_BASEURL = "https://docs.suitecrm.com/"
